[package]
name = "asm_interpreter"
version = "0.1.0"
authors = ["Simon Struck <simon@simonscode.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#alloc-cortex-m = "0.4.0"
#cortex-m-rt = "0.6.12"